version: '3.4'

services:
  mcswbot2:
    container_name: mcswbot2
    hostname: mcswbot2
    image: ${DOCKER_REGISTRY-}mcswbot2
    build:
      context: .
      dockerfile: mcswbot2/Dockerfile
    volumes:
      #- ./fonts:/app/fonts             # used to add custom fonts 
      - ./data:/app/data                # used to persist data between restarts/crashes
      - ./config.json:/app/config.json  # used to provide access to Telegram-Api